// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructuralElementManager.DataAccessLayer.Concrete.Context;

#nullable disable

namespace StructuralElementManager.DataAccessLayer.Migrations
{
    [DbContext(typeof(StructuralContext))]
    [Migration("20260104194627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StructuralElementManager.EntityLayer.Concrete.StructuralElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("FloorLevel")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialID");

                    b.ToTable("StructuralElement");

                    b.HasDiscriminator<string>("ElementType").HasValue("StructuralElement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StructuralElementManager.EntityLayer.Concrete.StructuralMaterial", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<double>("CompressiveStrength")
                        .HasColumnType("float");

                    b.Property<double>("Density")
                        .HasColumnType("float");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.ToTable("StructuralMaterials");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            CompressiveStrength = 30.0,
                            Density = 2.5,
                            MaterialName = "C30 Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 2,
                            CompressiveStrength = 35.0,
                            Density = 2.5,
                            MaterialName = "C35 Concrete",
                            MaterialType = 0
                        },
                        new
                        {
                            MaterialId = 3,
                            CompressiveStrength = 420.0,
                            Density = 7.8499999999999996,
                            MaterialName = "S420 Steel",
                            MaterialType = 1
                        });
                });

            modelBuilder.Entity("StructuralElementManager.EntityLayer.Concrete.StructuralBeam", b =>
                {
                    b.HasBaseType("StructuralElementManager.EntityLayer.Concrete.StructuralElement");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.ToTable("StructuralElement", t =>
                        {
                            t.Property("Height")
                                .HasColumnName("StructuralBeam_Height");

                            t.Property("Width")
                                .HasColumnName("StructuralBeam_Width");
                        });

                    b.HasDiscriminator().HasValue("Beam");
                });

            modelBuilder.Entity("StructuralElementManager.EntityLayer.Concrete.StructuralColumn", b =>
                {
                    b.HasBaseType("StructuralElementManager.EntityLayer.Concrete.StructuralElement");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Column");
                });

            modelBuilder.Entity("StructuralElementManager.EntityLayer.Concrete.StructuralSlab", b =>
                {
                    b.HasBaseType("StructuralElementManager.EntityLayer.Concrete.StructuralElement");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.ToTable("StructuralElement", t =>
                        {
                            t.Property("Length")
                                .HasColumnName("StructuralSlab_Length");

                            t.Property("Width")
                                .HasColumnName("StructuralSlab_Width");
                        });

                    b.HasDiscriminator().HasValue("Slab");
                });

            modelBuilder.Entity("StructuralElementManager.EntityLayer.Concrete.StructuralElement", b =>
                {
                    b.HasOne("StructuralElementManager.EntityLayer.Concrete.StructuralMaterial", "Material")
                        .WithMany("StructuralElements")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("StructuralElementManager.EntityLayer.Concrete.StructuralMaterial", b =>
                {
                    b.Navigation("StructuralElements");
                });
#pragma warning restore 612, 618
        }
    }
}
